# Generated by Django 4.0.3 on 2022-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='types_user',
            field=models.CharField(choices=[('paitent', 'Paitent'), ('doctor', 'Doctor')], default='doctor', max_length=10),
        ),
    ]
